server:
  port: 19081
grpc:
  port: 7565
  
spring:
  application:
    name: grpc-service-demo-server

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      grpc.port: 7565
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
        duration: 5

logging:
  level:
    com.grpc.service: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} | [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} | [%thread] %-5level %logger{36} - %msg%n'