server:
  port: 19082

spring:
  application:
    name: grpc-service-demo-client

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
grpc:
  targetServer: grpc-service-demo-server
  
logging:
  level:
    com.grpc.service: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'